### ISSUE TITLE
The iDREM is missing

### ISSUE THREAD

**Issue by Zhaoxu-Gao** [phoenixding/idrem#1]
When I used the iDREM for analysis, I found that the software is still DREM but not iDREM. And the iDREM Interactive Visualization can not be found.
![default](https://user-images.githubusercontent.com/20468832/38079833-7307a42e-3372-11e8-9c95-770bf5c05a73.png)

**Comment by phoenixding** [comment]
It's just a naming issue. We used the same name DREM here as it's part of the DREM software suite. 
We can change it to iDREM though if the name bothers you.
