### ISSUE TITLE
x11 Display on the cluster 

### ISSUE THREAD

**Issue by Sathish9** [phoenixding/idrem#2]
Hi,

I am running iDrem in batch mode in the cluster and getting the following error(please see below). I was told by our HPC team that iDrem does not have support to run in headless mode. Part of the code will have to be modified to run on the cluster. x11 display will only work in interactive mode.

ps. I did not have this issue in the Drem v2  software.

I hope you could help me to run this program on the cluster.

Regards,

Sathish

-----------------------------------------------------------------
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:77)
	at edu.umd.cs.piccolox.PFrame.<init>(Unknown Source)
	at edu.umd.cs.piccolox.PFrame.<init>(Unknown Source)
	at edu.cmu.cs.sb.drem.DREMGui.<init>(DREMGui.java:300)
	at edu.cmu.cs.sb.drem.DREM_IO_Batch.clusterscript(DREM_IO_Batch.java:1385)
	at edu.cmu.cs.sb.drem.DREM_IO_Batch.<init>(DREM_IO_Batch.java:261)
	at edu.cmu.cs.sb.drem.DREM_IO_Batch.<init>(DREM_IO_Batch.java:206)
	at edu.cmu.cs.sb.drem.DREM_IO.main(DREM_IO.java:5613)

**Comment by phoenixding** [comment]
@Sathish9 

Thanks for reporting this issue. 
Yes, we haven't tested the software in the cluster environment.  
I am fixing it now. I'll let you know when it's done. Thanks.

**Comment by phoenixding** [comment]
@Sathish9 

Hi, 

I just fixed the headless exception in the batch mode, tested on the cluster environment (slurm). 

```
52 
53 
54 
55 
56 
57 
58 
59 
writing Json..
Time: 2054914ms
[jund@r001 iDREM]$ 
```

Please download the latest version, it should be working now.  Make sure that the depending libraries folder (lib) is in the same directory of the idrem.jar file. 

Once you finished the running in the batch mode, you can find the results under the same directory of input expression data file.  Please refer to the readme for more details.

Let me know if you have further questions/problems.  Thanks.
