### ISSUE TITLE
Error when Integrating miRNA  expression and gene-miRNA interaction data

### ISSUE THREAD

**Issue by Sathish9** [phoenixding/idrem#3]
Hi,

I am getting the following exceptions when using miRNA data.

Null Pointer Exceptions and/or out of bounds exception when integrating miRNA  expression and gene-miRNA interaction data with different settings.

Is the miRNA names case sensitive?

when I select "Filter miRNA with no expression for regulatory data" in works and but wen finished- out of ArrayIndexOutOfboundsException

Hope you can help.

Regards,

Sathish

**Comment by phoenixding** [comment]
@Sathish9 

The miRNA names in the "miRNA"  expression file must be consistent with the those in the gene-miRNA interaction data.  Otherwise, it will report an error. 

For example, if you use "miR-16" in your expression file, but the gene-miRNA interaction data is using 
"mmu-miR-16". In that case, you will probably get the out of bounds exception.  Can you check whether this is the case? 

Also, can you provide your complete error log if possible? Thanks.

**Comment by Sathish9** [comment]
The Error Log:
java.lang.NullPointerException
	at edu.cmu.cs.sb.drem.RegulatorBindingData.estimateLogitW(RegulatorBindingData.java:1970)
	at edu.cmu.cs.sb.drem.RegulatorBindingData.normalizeRegulatorLevel(RegulatorBindingData.java:1901)
	at edu.cmu.cs.sb.drem.RegulatorBindingData.buildregTR(RegulatorBindingData.java:1591)
	at edu.cmu.cs.sb.drem.RegulatorBindingData.adjustBindingData(RegulatorBindingData.java:1387)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.<init>(DREM_Timeiohmm.java:411)
	at edu.cmu.cs.sb.drem.DREM_IO.clusterscript(DREM_IO.java:2418)
	at edu.cmu.cs.sb.drem.DREM_IO$8.run(DREM_IO.java:3058)
	at java.lang.Thread.run(Thread.java:748)

I am using Human but my expressions have all "0" for some miRNAs. Further Tis issue arises when Log Normalize/Log Normalize is checked. has it got to do with dividing by "0"?

Example

HSA-MIR-3650	0.687234	1.104398	0.659263	0.718137	0.688952	0.937032	0.286811	0.476367	0.500743	0.826254	0.674516	0.516552	0.653065	0.873643	1.530003	2.170584	0.93736	0.920119	1.078638	1.67615	1.129362	0.885117	1.42917	0.94821	0.80048	1.164343	0.989313
HSA-MIR-210	2.041439	2.287032	0.391531	0.583887	0.790521	0.783458	1.36621	0.495286	0.731813	4.829338	0.350586	0.068852	0.315929	0.974766	0.368944	0.578414	0.168522	0.606132	0.309334	0.974983	0.344791	0.182853	0.36601	0.652695	0.27606	0.474778	0.147881
HSA-MIR-143	0.036893	0.039303	0.060883	0	0.042841	0	0.038974	0	0	0.063621	0.045031	0.09064	0.053694	1.353855	0.195335	0.136677	0.085167	0.266431	0	0.699341	0.229866	0.09505	0.209069	0.147624	0.886284	0.110229	0.104264
HSA-MIR-2277	10.863195	10.644837	10.369808	11.215455	13.029478	11.887958	2.4901	10.579532	16.720593	6.056014	17.926748	10.048186	10.839578	0.83175	6.140023	12.717718	6.148471	4.180396	2.337256	4.436356	7.992999	6.90035	3.579614	4.78211	2.719663	3.598143	5.904353
HSA-MIR-449C	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0.605335	0	0	0	0	0	0	0	0	0	0	0
HSA-MIR-1343	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0	0
HSA-MIR-2278	0	0	0	0	0	0	0.054595	0	0	0	0	0	0	0	0	0	0	0	0	0.097046	0	0	0	0	0	0	0

Further , the file human_miRNA_interactions.txt has over 400,000 duplicate rows. I converted these IDs to Uppercase to Match my expression Data.

**Comment by phoenixding** [comment]
@Sathish9 

Thanks for this information. 
The error happens when normalizing the miRNA expression data. 
BTW, did you remove the first row of the human_miRNA_interactions.txt, it's something like:

MIRNA	GENE	INPUT


You would have to keep the header row.  

I can't replicate your errors on my side. If possible, could you please send me
some example files, which can replicate your problem? Thanks.

**Comment by Sathish9** [comment]
I have the heading. Please find attached files.

[PCx_IPC_miRNA.txt](https://github.com/phoenixding/idrem/files/2070871/PCx_IPC_miRNA.txt)
[PCx_S1C_Filtered_miRNA.txt](https://github.com/phoenixding/idrem/files/2070872/PCx_S1C_Filtered_miRNA.txt)
[human_miRNA_interactions_Uppercase.txt](https://github.com/phoenixding/idrem/files/2070873/human_miRNA_interactions_Uppercase.txt)

**Comment by phoenixding** [comment]
@Sathish9 
Thanks.  But to test run this, I would also need the gene expression data.
I already downloaded the above data you send, I can delete/hide all your data once I downloaded them if you want to keep your data privately.

Sorry for the inconvenience, I will try to get the problem solved in this week.
Regards

**Comment by Sathish9** [comment]
PCx_S1C_Filtered_miRNA.txt is the gene expression data

**Comment by phoenixding** [comment]
@Sathish9 
I see. I was confused by the name. 
Thanks. Get back to you soon. 

Regards

**Comment by Sathish9** [comment]
[PCx_S1C_miRNA.txt](https://github.com/phoenixding/idrem/files/2070935/PCx_S1C_miRNA.txt)
Sorry this is the correct miRNA file

You can run it and recommend the optimum parameters for the model

**Comment by phoenixding** [comment]
@Sathish9 
Thanks.  It's a  bug in 'Log normalize data' normalization function.  
You can convert your data into log2 space (e.g. log2(x+1)) and then use the second normalization option (Normalize data), it should be working.  I'll get the bug fixed as soon as I can. 

Sure, I can run on my side and let you know the best parameters. 
 
Thanks a lot for reporting the bug.

Regards

**Comment by Sathish9** [comment]
Thanks!

Further, I got another question!

It would be nice for iDREM to accept variable number of repeats for Gene and miRNA expression in the same time points. Because I got data where certain time points with no repeats and certain time points with 3 repeats. Is there a solution for this?

Regards,

Sathish

**Comment by Sathish9** [comment]
By looking at my RNA-seq expression data, I think its already in log2 scale.  

http://rstudio-pubs-static.s3.amazonaws.com/196822_f03ee582b3c740c1bbc5fb9c3c64bbc3.html

I tried them before, however the scale in x axis of the Java interface is huge and I am unable to see the split. The web interface looks normal. Moreover the Transcription factors listed in Java Interface and web interface are different. Please see attached figures.
![test_image](https://user-images.githubusercontent.com/8219421/40979418-1488007e-6919-11e8-82b4-ff1474dbea03.jpg)
![screen shot 2018-06-05 at 11 31 01 pm](https://user-images.githubusercontent.com/8219421/40979432-22200f88-6919-11e8-8f8e-510a9fafbcbc.png)

Regards,

Sathish

**Comment by phoenixding** [comment]
@Sathish9 
It does not like a log2 expression. 
For example, the following is an example from your expression data
LASP1	68.038087	76.417347	75.951683	73.7443	72.975955	82.845066

As for the difference between the Java Interface and web-interface, they are based on the same model and the results are the same. But the visualization is slightly different.   In java model, the up-regulated TFs and down-regulated TFs are ranked separately, and also the TFs and miRNAs are also ranked differently.  But in the web interface, we put them all together so that the users can find the most significant ones (no matter what type it is) more easily. 
Therefore, you see different orders. But if you look at the p-values of these TFs/miRNAs, you will find them the same.

**Comment by Sathish9** [comment]
Thanks!
I want to compile a list of all the significant regulators per model and I used to do that in the java interface. How can I do that in the Web Interface. Further the expression trajectories in the Java Interface is not spread(i.e. sitting close to zero) whereas in the web Interface, it is clearly visible. How can I alter the x axis scale in the Java Interface?

**Comment by phoenixding** [comment]
@Sathish9 

To get the regulators in the web interface, you can just click the node (set the "click" option as "Regulator" under the global config panel first).  
![screenshot from 2018-06-05 22-28-50](https://user-images.githubusercontent.com/21684886/41012542-fb97da16-690f-11e8-893b-ed42faaca27a.png)

For the expression trajectories in the java interface, you can use the interface options 

change the Y-axis scaling factor, you will be able to adjust the layout. 
 
![screenshot from 2018-06-05 22-26-20](https://user-images.githubusercontent.com/21684886/41012465-9aa846dc-690f-11e8-9287-1c04630fbf81.png)

**Comment by Sathish9** [comment]
How do I save all the significant regulators(TFs and miRNAs) to a text file?

**Comment by phoenixding** [comment]
@Sathish9 
If you want to do it manually, you can click each node and copy out the regulators. 
But this would be very ineffective. You can also get all the regulators (for given rank cutoff) systematically
from the Json file under the results folder.  I will add the description of the json file in the markdown file later this week together with the normalization bug fix.

**Comment by Sathish9** [comment]
I noticed that you have done a bug fix. When running the updated program with log normalize option, using only the gene expression data, the program works as expected. However, when miRNA expression is included in the analysis, the same java.lang.NullPointerException appears.

**Comment by phoenixding** [comment]
@Sathish9 
Still working on it. The fix is not done yet.
I'll try to get it fixed later this week, I'll keep you posted.

**Comment by phoenixding** [comment]
@Sathish9 

Hi, I just fixed the bug and also added a few more functions (e.g. download json file from the web page). 
Please download and use the latest version.

The format of the json file can be found in the readme. Basically, you can extract the information you needed (TFs for all nodes) from the json file.   

For the datasets, I recommended the following parameters:

![screenshot from 2018-06-08 22-24-57](https://user-images.githubusercontent.com/21684886/41188289-254c02f8-6b89-11e8-9250-6ae00164b284.png)


![screenshot from 2018-06-08 22-25-16](https://user-images.githubusercontent.com/21684886/41188297-2e5295f6-6b89-11e8-8d7f-d744688234db.png)

![screenshot from 2018-06-08 22-25-38](https://user-images.githubusercontent.com/21684886/41188298-3331272c-6b89-11e8-9786-abba516d458d.png)

result:

![screenshot from 2018-06-08 22-25-58](https://user-images.githubusercontent.com/21684886/41188305-47ea2bdc-6b89-11e8-91e4-6550b5422db3.png)


!!!!NOTE!!!
Please use at least 8G RAM  for your data, 4G seems not enough.

java -Xmx8g -jar idrem.jar 

Let me know if you have further questions.

**Comment by Sathish9** [comment]
Thanks for the updates!!!

I noticed that you used an updated version of my miRNA expression file called miRNA2. What changes did you make? Because I am getting the same error with my original files.

**Comment by phoenixding** [comment]
@Sathish9 

No, I changed nothing. 
I used the second miRNA you sent (you mentioned that this one is the right one) and I renamed it to miRNA2

Here are gene expression and miRNA expression files I have used:

gene expression:
[PCx_S1C_Filtered_miRNA.txt](https://github.com/phoenixding/idrem/files/2086962/PCx_S1C_Filtered_miRNA.txt)

mirna expression:
[PCx_S1C_miRNA2.txt](https://github.com/phoenixding/idrem/files/2086963/PCx_S1C_miRNA2.txt)

I just tried again, it's just working without any exceptions. 
![selection_001](https://user-images.githubusercontent.com/21684886/41191991-b6a9efee-6bc5-11e8-8042-c6f3909e6515.png)


 Can you double check whether you have used the latest version?
Thanks.

**Comment by Sathish9** [comment]
I deleted the old version completely and replace it with the new version. When I executed the app with your specified settings, including filter miRNA with no expression from regulatory data - checked, the execution is progressing well. However wen I end the search I am getting the following error message.

![screen shot 2018-06-10 at 9 56 44 am](https://user-images.githubusercontent.com/8219421/41197104-cd30ffd4-6c95-11e8-8d7d-573f47826534.png)

But when I uncheck "filter miRNA with no expression from regulatory data" I am getting the NullPointer Exception. My miRNA expression file has uppercase miRNA IDs  where as the default miRNA Interactions file has lowercase miRNA IDs. Is this application case sensitive. Further, I am using Mac and Linux platforms. Are you running this on windows? because the end of line characters are different in these platforms. When I used the modified version(with Uppercase IDs) of miRNA expression file with the miRNA expression data, I am getting NullPointer Exception on both settings for "filter miRNA with no expression from regulatory data".
Are you getting any miRNAs as regulators in your final output? because I thing all miRNAs will get filtered off when "filter miRNA with no expression from regulatory data"?

**Comment by phoenixding** [comment]
@Sathish9 

I am using Linux (both linux mint and Manjaro), they are both working fine.
Yes, I got everything expected including the miRNAs as the regulator. 

You can download the results using the link below:
http://jund.andrew.cmu.edu:8080/tmp/idrem_results_tmp/result.tar.gz

I noticed that you used a customized TF-gene interactions file.
Is it possible that there are some formatting issues with your customized file?

Can you try the default human TF-gene interactions file to see whether you still encounter the same problem? (as the following)

![screenshot from 2018-06-08 22-24-57](https://user-images.githubusercontent.com/21684886/41197403-35a1e1c0-6c2b-11e8-8d08-8a99fdf794e9.png)

It's just working fine in my end with the inputs you provided.

I just tested your microRNA-gene interactions file on my end, it's also working fine. 

![screenshot from 2018-06-09 22-02-24](https://user-images.githubusercontent.com/21684886/41197564-44ef3ca8-6c31-11e8-9c7f-e93747b265c1.png)

Also, maybe you can try to download the software directly here:
http://jund.andrew.cmu.edu:8080/tmp/idrem_results_tmp/idrem-master.zip

This is the exact package I used to test your inputs.

**Comment by Sathish9** [comment]
I ran the app on my Mac with your settings and files util I had 16 paths. And when I clicked display model I am getting the following error.

java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.computeStats(DREM_Timeiohmm.java:4352)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.displayTempMap(DREM_Timeiohmm.java:1104)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2172)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandaddhelp(DREM_Timeiohmm.java:2164)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.traverseandadd(DREM_Timeiohmm.java:2148)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.searchstage1(DREM_Timeiohmm.java:1213)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.<init>(DREM_Timeiohmm.java:453)
	at edu.cmu.cs.sb.drem.DREM_IO.clusterscript(DREM_IO.java:2418)
	at edu.cmu.cs.sb.drem.DREM_IO$8.run(DREM_IO.java:3058)
	at java.lang.Thread.run(Thread.java:748)

What do you think is causing this?

**Comment by phoenixding** [comment]
@Sathish9 
You shouldn't get 16 paths, it should stop at 12 paths.  
I encountered the problem you mentioned before the fix, but it has been fixed already.


It must be something wrong, did you use the package in the above link?
Did you use the default TF-gene interactions file?

I am not quite sure about the reasons for the error in your case as it's working just fine on my end. 
But, I am suspecting that you probably still used an out-dated version.

I just re-pushed the software package in case the github one is updated.

**Comment by Sathish9** [comment]
I downloaded from the above link you sent and ran it again but no luck. I use the TF-Gene Interaction files and miRNA interaction files. 

However when I used my own log2 version of the expression files with Normalize data option, it works.

**Comment by phoenixding** [comment]
@Sathish9 

Good.  As for the log normalization option, it did work perfectly well on my end after the fix, tested on a few computers.  I just re-pushed the code to the github, if you got the time and the willing, you may try to test it again.  When you run it, make sure use at least 8G ram. I think it should be working.  

If it fails again and you really want to figure out the reason why it's not working on your end, I can help you check it remotely (e.g. via teamviewer).

**Comment by Sathish9** [comment]
The new code on GitHub seems to be working. I will keep you posted.

**Comment by Sathish9** [comment]
Hi

I was trying to open a model which was executed on the cluster. However, for some models I am getting the following error. I used the exact same setting to open the model on my Mac.

java.lang.IllegalArgumentException: Number of time points in the initial model (25) does not match number of time points in the data (24)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.readInitTree(DREM_Timeiohmm.java:1867)
	at edu.cmu.cs.sb.drem.DREM_Timeiohmm.<init>(DREM_Timeiohmm.java:435)
	at edu.cmu.cs.sb.drem.DREM_IO.clusterscript(DREM_IO.java:2418)
	at edu.cmu.cs.sb.drem.DREM_IO$8.run(DREM_IO.java:3058)
	at java.lang.Thread.run(Thread.java:748)

**Comment by phoenixding** [comment]
@Sathish9 
Basically, this error tells that the number of time points in your initial model (the one you saved) and the one you used to re-open the saved model (either gene expression file or microRNA expression file) is different.

Can you double check whether you are using the same input expression files for both the saved model and the re-open model?  Also, for the results you got on the clusters, you should also have the web-page results, which should have all the results you needed. You can also try to use that results.

**Comment by Sathish9** [comment]
Thanks. I identified the problem.

I want to know what databases you used to construct the human miRNA interactions. Did you use experimentally validated interactions or predicted interactions? I have attaached some updated database links for your information. 

comprehensive (also Include miRTarBase)
http://mirwalk.umm.uni-heidelberg.de/

Experimentally validated (miRTarBase)
http://mirtarbase.mbc.nctu.edu.tw/php/index.php

**Comment by phoenixding** [comment]
@Sathish9 

Thanks. 
For the human miRNA interactions, we used the miRanda predictions (http://www.microrna.org/). We did not collect all those experimentally verified ones such as mirTarbase or Tarbase as it's still quite sparse, # of validated targets are relatively limited. 

But if you prefer those microRNA targets, you can definitely use the "user-defined" option.  
Just make sure the format is right.
