### ISSUE TITLE
How to generate data from a trained IOHMM model given the iDREM model file

### ISSUE THREAD

**Issue by djinnome** [phoenixding/idrem#4]
Hi folks,

We are interested in taking the learned IOHMM probabilistic graphical model from iDREM and treating it as a causal model that we can perform interventions on (for example, by trying to generate expression data from a TF knockout  intervention by mutilating the learned model and comparing it with expression data from an actual TF knockout).  When we look at the model file output, I am unclear how to relate that to the underlying IOHMM.   For example, if we were to convert the model file to an [IOHMM Unsupervised json model](https://github.com/Mogeng/IOHMM/blob/master/examples/models/UnSupervisedIOHMM/model.json), could I use the model  intercept and coefficients directly as inputs to the IOHMM json file?

Also, in figure 1D of the original DREM model, transition probabilities for each target gene are learned, but I don't seem to be able to locate where those transition probabilities are stored. (Or perhaps they are automatically calculated from the model parameters file?)

I hope this makes sense, I would be happy to clarify if it isn't obvious what we are asking.

Sincerely

Jeremy  Zucker and @david-degnan

**Comment by phoenixding** [comment]
@djinnome 
Hi Jeremy, thank you for your interest in using our tool.
But still, I am not quite sure whether I fully understand your request.
We can schedule a zoom meeting to talk about this if you want　
You can reach me via my email: jund  at cs dot cmu dot edu
