### ISSUE TITLE
Info request about idrem

### ISSUE THREAD

**Issue by demis001** [phoenixding/idrem#5]
@phoenixding 

I am trying to create a figures for publication similar to Figure 3 in this paper (https://insight.jci.org/articles/view/131597). Do you think `idrem` will output similar figures? I tried DREM2 and I haven't reproduce similar figures. It looks like they used `networkD3` R package, I don't know how they input DREM2 output to this package.

Any idea?

@demis001

**Comment by phoenixding** [comment]
@demis001 
Yes, that figure3 was generated by iDREM.
One major extension of iDREM is that we incorporated an interactive visualization (powered by JavaScript) that can generate a variety of plot based on user's inputs. 

Since you probably have the results ready in DREM2, you can directly use it in iDREM (compatible) 
![Screenshot from 2020-09-21 20-46-07](https://user-images.githubusercontent.com/21684886/93834956-a3424f00-fc4b-11ea-85f6-182712f6e985.png)

Simply upload the ".model" file from your drem2 output to the "Saved Model File" filed as shown above.  All other parameters MUST keep exactly the same as your previous run with DREM2. 
Rerunning iDREM with this configuration will reproduce what you got in DREM2 (together with a visualization page). 

Under the Path function panel in the html visualization page, you will be able to generate the sankey plots.   Let me know if you have further questions.

**Comment by demis001** [comment]
@phoenixding 

Thank you for response, I really appriciate! I will try tomorrow and let you know if I got some error.  Keep the issue open so that I will update in case.

Best,
@demis001

**Comment by demis001** [comment]
@phoenixding 

I am a confused with the following options in DREM2.

My data is an RNA-Seq in Log2 space 0-16 value coming from DESeq2, I have generated the median for each time point after log trasformation and used as input for DREM2 , I have a time point 3, 7, 24, 72, 100. Time point 3 should be used as time 0 in DREM2. 

Which options I should select:

2. Normalized data  OR
3. No normalization/add 0

@demis001

**Comment by phoenixding** [comment]
@demis001 
You should use normalized data (if you want to see the expression change w.r.t the first time point).
Add 0 => add a column of 0 expression as the first time point.

In your case, you should choose 2 (normalized data)

**Comment by demis001** [comment]
Thanks!

@demis001

**Comment by demis001** [comment]
For some reason, the model.txt file isn't recognized by `idrem`. It throughs an error.

**Comment by demis001** [comment]
"No a valid saved model file"

**Comment by phoenixding** [comment]
@demis001 
There must be something wrong. 
The model file should be ending with the " .model" suffix.  Can you provide a screenshot of the result files from your DREM2 running? Thanks.

**Comment by demis001** [comment]
I saved as ".txt", let me save as ".model"

**Comment by demis001** [comment]
@phoenixding 

It is working now, how to save the image in 'idrem' html page as vector graphics? I got close image to the one shown on that paper, but it sill require label and change line strok size and color. How to save the image as vector graphics? Is it possible?

@demis001

**Comment by phoenixding** [comment]
@demis001 
Yes, its supported. But you have to use Microsoft Edge browser
![image](https://user-images.githubusercontent.com/21684886/93842072-9d586800-fc63-11ea-82e3-7adc36054d97.png)

Right click the graph and choose "save as svg" in the drop-down menu as shown above.
For chrome and Firefox, I believe you can download svg directly.  
We will fix this when we have time.

**Comment by demis001** [comment]
I am using mac pro, nothing works to save the image. I have downloaded and tried 'save as', I don't see any `svg` option in drop down menu. Tired firefox and google chrome too. 

<img width="1336" alt="Screen Shot 2020-09-21 at 11 57 36 PM" src="https://user-images.githubusercontent.com/8713514/93843092-dba35680-fc66-11ea-966b-7815a4823290.png">

@demis001

**Comment by phoenixding** [comment]
@demis001 
Unfortunately, you can't download svg using firefox, chrome, or safari. 
For now, you have to use  the Microsoftware edge browser to download the figure in svg format. 
Sorry for the inconvenience.

**Comment by demis001** [comment]
I have download Microsfot edge, that was the screenshot I posted from Microsoft edge. It doesn't have svg option after right click and save as ...

**Comment by demis001** [comment]
The Sankey diagram also open in black page, the image is too big. Unable to zoom out that one either. If it does zoom out, I can print save as pdf that image.

**Comment by phoenixding** [comment]
@demis001 
You can zoom out using firefox and then you can print it to pdf.

**Comment by demis001** [comment]
Thanks! for your help, I will try tomorrow and let you know. I  have some technical question too. For example the first diagram shows 0(UID) instea of the first time point. But, the iDREM and DREM2 result shows the first time point as time 0.  I will play with it and ask you the detail tomorrow.

**Comment by demis001** [comment]
The GO table is different for the same sample  between DREM2 and iDREM. All option are the same, saved the model from DREM2 and loaded to iDREM. 


<img width="1462" alt="go_table_drem2_idrem" src="https://user-images.githubusercontent.com/8713514/93905424-f5758580-fcc8-11ea-96f7-df2b2412dc4f.png">

**Comment by phoenixding** [comment]
@demis001 
The saved model only preserve the tree trajectory, TFs, and genes. 
The enriched GO terms are not saved. They are re-calculated in iDREM based on the assigned genes for each path.  However, the GO enrichment functions should be the same.  The different GO term results might be caused by different annotation files.    

The GO annotations included in DREM2 or iDREM might become out-dated.
In the visualization page, you can perform the GO enrichment analysis (with updated tools) by shift+clicking the node.

![image](https://user-images.githubusercontent.com/21684886/93907296-2656ba00-fccb-11ea-83b6-232ee1e6857b.png)
You can choose "PANTHER" or "Toppgene" for the enrichment analysis.
Those two functional enrichment tool were well maintained and updated. 

But I would expect that the results are pretty much similar.

**Comment by demis001** [comment]
Thanks! I will double check that. 

In the Sankey diagram, how the cut off made? Would you please tell me that, there is no button to change the filter.

**Comment by phoenixding** [comment]
@demis001 
Those are the options to filter GO terms
![image](https://user-images.githubusercontent.com/21684886/93911309-39b85400-fcd0-11ea-8911-8db6c19fc207.png)

GO term rank cutoff => top ranked GO terms for each path will be kept.
Sankey TF rank cutoff=> a rank cutoff to show/hide TFs.
Go terms  with < ? genes= > filter top-level GO terms (usually with a larger # of genes).

**Comment by demis001** [comment]
How about adjusted p-value cut off?  How to restrict to signficant go term only, let say corrected p-value < 0.05

**Comment by demis001** [comment]
I thought the sanky diagram make an aggrigate summary plot for the data generate under the go table which has a detailed statistics.

**Comment by phoenixding** [comment]
@demis001 
we decided to filter the GO terms using the rank instead of corrected p-values.  
The top ranked GO terms should be already significant. 
The reason why we are not using corrected p-value <0.05 as the cutoff is:
it will result in too many (hundreds of) significant GO terms, which can't be visualized in a single sankey plot.

**Comment by demis001** [comment]
@phoenixding 

We have three experiment with time series (three DREM model). We want to extract all Go-term and all TF from each experiment  in DREM and iDREM. Would you please help us how to better extract this information and compare what are the difference GO-term and TF between the three experiment. Every time we clicked on different part of the node, we get different GO-tem and TF, we don't know the approriate way to extract all TF and All GO term in three experiment. 

To give you a little bit about the expirment, we have a stem cell treated with three media and measured the gene expression at time 3h, 24hr, 3day, 7days and 17 days.  We want to see what are the diffent GO term  and TF between the three media. Would you please suggest us the better way to do this? I am also asking if you are willing to join us via zoom if it is complicated to show the approach in text. 

Best,
@demis001

**Comment by phoenixding** [comment]
@demis001 
You can systematically extract all TFs and GO terms for all nodes in the plot using the JSON file. 
You can use the extractJson.py script in the utils folder to generated a readable JSON file.
```
python extractJson.py DREM.json
```
DREM.json file can be found under the idrem visualization folder. 

The script will output a formatted JSON file that can be parsed easily. 
The first element is the list of all nodes. 

```
Pdb) Nodes=tjson[0]
(Pdb) node=Nodes[1]
(Pdb) node.keys()
dict_keys(['parent', 'children', 'nodeID', 'nodetime', 'nodeMean', 'nodeSigma', 'genesInNode', 'ETF', 'goNode'])
(Pdb) node.ETF
```
besides the root node(node 0), all other nodes are associated with a lot of attributes, which include ETF and goNode.   These are the information that you are looking for

ETF: all TFs with p-values
goNode: all go terms for the node (you can choose a p-value to cut).

==============================================================

If you want to compare the TFs and GO terms from 3 different models (different treatments), you should compare at each time point. The TFs function dynamically in the entire temporal process. You should not just compare all the TFs in 3 conditions in general (Even you get the same set of TFs from 3 models, they might function at different time points). Instead, you should compare the TFs/GO terms at each time point in all 3 models. You can group paths into 3 categories (up-regulated->top, stable->middle, and down-regulated->bottom). At each time, collect all TFs/GO terms for each of the categories.  You can then compare whether different TFs/GO terms are observed for top/middle/bottom paths at each time point. 

I can meet with you via Zoom to discuss this application if you have further questions,  but I won't be available until Nov.1.

**Comment by demis001** [comment]
@phoenixding 

Thank you very much! I have  a couple of question:

How `DREM.json` knows which model to use?  Would I run each experiment in dedicated folder? Is this file dynamically created during each run? I am easily perse the json file if I generate the json output. 

From the README file, I see this "This plots the Sankey diagram to show the function (GO terms) and regulators (miRNA/TFs) associated to each path". How this GO term sorted out for each path, if each node is different GO term?

 I will give a try. If I need more clarification, I will arrange zoom call with one of my colleague (professor) after Nov1. 


Best,
@demis001

**Comment by phoenixding** [comment]
@demis001 
Yes, you can run them in separate folders. 
The output directories are named with the same prefix as the input expression file.
If your input expression files are different, you will be able to find the corresponding result folder.
Inside each folder, you will be able to obtain the json file.

GO terms only change after the split (divergence) node.  Go terms will stay unchanged if there is no split event.   For each path, you will only have 1 set of GO terms. 

To help you understand,  
    
![Untitled presentation](https://user-images.githubusercontent.com/21684886/96321778-a9c2ad00-0fe4-11eb-80af-5f9b62b8db8b.jpg)



This tree only has 1 split  (1-2,3)
Technically speaking 1 is also part of A (top path), but you can't use the GO terms for 1 to represent path A as 1 is also the parent node of path B (bottom path).  

To represent path A, you should use its unique nodes (e.g., the leaf node 6)
The GO terms on node 2,4,6 are the same as those nodes have the same sets of genes.  

If you have further questions, I can talk with you on Zoom after Nov.1st

**Comment by demis001** [comment]
@phoenixding 

I got a chance to try the python script today, but I am getting the following error while loading the json object. Tried both under python3 and python2. I have checked the script from the python interactive terminal and in both cases this is the one line failed.  I have tried both json and simplejson, both gave me the same error.

Python3:
```
>>> tjson=json.loads(lf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 6896285 (char 6896284)
```

Python2:

```
2.77474116928461"],["19189","AC136628.3","3.23720648326192","3.16200290561414","3.86437556371216","2.70297226870175","2.16189500565336"],["19190","SLCO5A1","3.05291743441865","3.02553198585086","3.16385688930132","2.10242905932626","3.19992837964914"],["19191","EGR3","7.93790863202554","8.67366331569346","8.0043451109455","7.64866188820371","6.81891749061603"]],null,null,]'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> tsjson=json.loads(lf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by demis001** [comment]
I don't know what happened, "accidentally" closed the issue.
