### ISSUE TITLE
Extract Json file

### ISSUE THREAD

**Issue by demis001** [phoenixding/idrem#6]
Sorry, I accidentally closed the previous issue. 

I got a chance to try the python script today, but I am getting the following error while loading the json object. Tried both under python3 and python2. I have checked the script from the python interactive terminal and in both cases this is the one line failed. I have tried both json and simplejson, both gave me the same error.

Python3:

```
>>> tjson=json.loads(lf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Users/demis001/opt/anaconda3/lib/python3.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 6896285 (char 6896284)
```
Python2:

```
2.77474116928461"],["19189","AC136628.3","3.23720648326192","3.16200290561414","3.86437556371216","2.70297226870175","2.16189500565336"],["19190","SLCO5A1","3.05291743441865","3.02553198585086","3.16385688930132","2.10242905932626","3.19992837964914"],["19191","EGR3","7.93790863202554","8.67366331569346","8.0043451109455","7.64866188820371","6.81891749061603"]],null,null,]'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>> tsjson=json.loads(lf)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/demis001/opt/anaconda3/envs/python2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by phoenixding** [comment]
@demis001  
can you share with me  your json file? I'll take a look

**Comment by demis001** [comment]
Attached, Please  rename the `DREM.DOCX` to `DREM.json`
[DREM.DOCX](https://github.com/phoenixding/idrem/files/5431276/DREM.DOCX)

@demis001

**Comment by demis001** [comment]
Would you please tell us what time works for you Monday November 2 from 9-5pm eastern time? My be 20-30 min zoom. I will send you the link with passcode

**Comment by phoenixding** [comment]
@demis001 
For some reason, there is an additional ", " at the end of your json file.
You have to remove it. 
You can add the following code after line 9
lf=lf[:-2]+']'

or you open the joson file, delete the last ',' after the last "null"

As for meeting time, Nov 2nd, 2pm eastern time works for me.

**Comment by demis001** [comment]
Thanks! I will try it.

Here is the zoom info for Nov2 2pm

Join Zoom Meeting
https://ncsu.zoom.us/j/91552496132?pwd=dmZ3U3B5TE5RT2I0QmVMUFc1bEVVUT09

Meeting ID: 915 5249 6132
Passcode: 641612
One tap mobile
+17866351003,,91552496132#,,,,,,0#,,641612# US (Miami)
+19292056099,,91552496132#,,,,,,0#,,641612# US (New York)
@demis001

**Comment by demis001** [comment]
@phoenixding 

I got some wierd result (see the vertical line on the bottom tree) after using the custom TF. This happned for two media. One seems similar to the previous result. Do you know why this happens? Is this normal?  

See the attached image.

![image_file](https://user-images.githubusercontent.com/8713514/98200172-0980e980-1efb-11eb-809e-7d1d122415b6.png)

Second question:

I used the following format, the lebel on the figure doesn't seems fit what I have provided? Do you know why it shifted to the right?


Spot | UID | GM_DMSO_Median_3h | GM_DMSO_median_24h | GM_DMSO_median_3d | GM_DMSO_median_7d | GM_DMSO_median_17d
-- | -- | -- | -- | -- | -- | --
1 | FKBP5 | 8.65805799738727 | 8.73802525254617 | 6.72723380206989 | 6.75324283494209 | 7.57643357204655
2 | IRS2 | 7.96700861249989 | 7.25154259724371 | 9.45596578624527 | 9.10839103732948 | 9.08053600061206
3 | ZFP36L2 | 10.8761023672962 | 11.6714814848495 | 11.4055959997379 | 11.7971460983172 | 12.2011893702766
4 | HMOX1 | 12.7359365512779 | 9.52568706942057 | 10.3770743411579 | 9.63543422108012 | 10.3798506772213

@demis001

**Comment by phoenixding** [comment]
@demis001 
No, it's not.
I suspect that there might be some formatting issues for the customized TF-gene interaction data.
Could you share the TF-gene interaction data that you used and the results folder?
You can email me jund@cs.cmu.edu if it's not convenient here, I will help you fix it.

**Comment by demis001** [comment]
I sent it.
